apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-markdown-sample
spec:
  portal:
    registration:
      type: anonymous
    sessions:
      maximum: 1
  workshops:
  - name: lab-markdown-sample
    reserved: 0
    expires: 120m
    orphaned: 15m
